Update continuous-monitoring.yml (#38)
* Update continuous-monitoring.yml

add 3 retries in smoke test

* Update continuous-monitoring.yml

diff --git a/.github/workflows/continuous-monitoring.yml b/.github/workflows/continuous-monitoring.yml
--- a/.github/workflows/continuous-monitoring.yml
+++ b/.github/workflows/continuous-monitoring.yml
@@ -9,24 +9,10 @@ jobs:
     name: Pull X-Ray .NET agent from github release
     runs-on: ubuntu-latest
     steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-
       - name: Pull X-Ray .NET agent from github release
         id: distribution-availability-github
         run: |
-          wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X64.msi
-          wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X86.msi
-
-      - name: Publish metric on X-Ray .NET agent distribution availability (Github)
-        if: ${{ always() }}
-        run: |
-          if [[ "${{ steps.distribution-availability-github.outcome }}" == "failure" ]]; then
-            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentGithubDistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 1 --timestamp $(date +%s)
-          else
-            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentGithubDistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 0 --timestamp $(date +%s)
-          fi
+          (echo "===== Attempt: 1 ====" && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X64.msi && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X86.msi) || \
+          (echo "===== Attempt: 2 ====" && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X64.msi && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X86.msi) || \
+          (echo "===== Attempt: 3 ====" && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X64.msi && wget https://github.com/aws/aws-xray-dotnet-agent/releases/download/v2.10.0-beta.1/aws-xray-dotnet-agent-installer-beta-X86.msi) || \
+          (echo "===== No more retries. Failed! ====" && exit 1)
